name: Run Notebooks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  execute-notebooks:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert

    - name: Execute Notebooks
      run: |
        for notebook in $(find . -name "*.ipynb"); do
          echo "Running $notebook"
          jupyter nbconvert --to notebook --execute "$notebook" --inplace --ExecutePreprocessor.timeout=600
        done

